server:
  port: 8081

spring:
  application:
    name: serverA

  cloud:
    nacos:
      #discovery:
      # server-addr: 127.0.0.1:8848
#      server-addr: 127.0.0.1:8848
#      namespace: e4e90f45-dd1e-4457-8859-e2c4c127fd1a
      config:
        server-addr: 127.0.0.1:8848
        group: dev
        namespace: e4e90f45-dd1e-4457-8859-e2c4c127fd1a
      discovery:
        group: dev
        server-addr: 127.0.0.1:8848
        namespace: e4e90f45-dd1e-4457-8859-e2c4c127fd1a